server:
  port: ${GATEWAY_SERVER_PORT}

spring:
  application:
    name: ${GATEWAY_APPLICATION_NAME}

  cloud:
    gateway:
      forwarded:
        enabled: true

      routes:
        - id: test_route
          uri: ${TEST_ROUTE_URI}
          predicates:
            - Path=${TEST_ROUTE_PATH}
          filters:
            - RewritePath=${TEST_ROUTE_REWRITE}
        
        - id: iam_route
          uri: ${IAM_ROUTE_URI}
          predicates:
            - Path=${IAM_ROUTE_PATH}

        - id: billing_route
          uri: ${BILLING_ROUTE_URI}
          predicates:
            - Path=${BILLING_ROUTE_PATH}
          filters:
            - RewritePath=${BILLING_ROUTE_REWRITE}

        - id: reservation_service
          uri: ${RESERVATION_ROUTE_URI}
          predicates:
            - Path=${RESERVATION_ROUTE_PATH}
          filters:
            - RewritePath=${RESERVATION_ROUTE_REWRITE}

        - id: invitation_route
          uri: ${INVITATION_ROUTE_URI}
          predicates:
            - Path=${INVITATION_ROUTE_PATH}
          filters:
            - RewritePath=${INVITATION_ROUTE_REWRITE}

        - id: notification_route
          uri: ${NOTIFICATION_ROUTE_URI}
          predicates:
            - Path=${NOTIFICATION_ROUTE_PATH}
          filters:
            - RewritePath=${NOTIFICATION_ROUTE_REWRITE}    

logging:
  level:
    org.springframework.cloud.gateway: ${GATEWAY_LOGGING_LEVEL}