### Créer une souscription (via Gateway)
POST http://localhost:8080/billing
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXRzYSIsImlhdCI6MTc0NzY5OTI2OCwiZXhwIjoxNzQ3NzAyODY4fQ.ItVcAg62LHJygGOz04SP1UQyyQO64URg38Iub9FAcYwyT9NcQOBqMtQ6ZrCZV8a3RdXkgkTVygDQctTrjqpmBPFB_vd-0W0p-qFjqToT_-hYS6LQiLOQX_mIk7I1k4MIz2QJQcUGcY6015zCn015Ep4iD-gLQkeRq3qG26q8FNESTR1mLQv88XtItEIkRaIfwduxnayJCMm2pBAExitzQ1uZXT_5J_V1EloEP0x4z3KzUwvdBihy-fppHwdfidu51FCgEj8fB_XFbUKfZEo5ipGznmMywx--pu_qOXqQC8VPkGKXbu9VPPQMIIR8x-9eyqxyPV-MH3fNaVGFTdATwA
Content-Type: application/json

{
  "agencyName": "AgenceBeta",
  "planType": "Standard"
}

### Lister les souscriptions (via Gateway)
GET http://localhost:8080/billing
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc0NjgxODU1MiwiZXhwIjoxNzQ2ODIyMTUyfQ.gu5a0tGu2yV7WpCuyBb1I2YTKAj6u43xphDl5OipXqUb5oQl5Od5BIZVdmS1LVy8RN_Nox80WiF-NAn14w5UJfW-SteP3jIpOT0TiLD_jxvnRdLActhC7Wq3p5RohImL8F3ms1ujhYMiTxGjSR-Z2LOfOMDTR3QlT9yhS8UUtZzEzgM4BZCTPJFgChWuCGFUCz2oqktNIHzDwWJHPNlekS60_WrebdPk6LRN5jUMUlSuSRa2DAyDJtSQmJUdZqaIoy84vUbf3KPrnUGKFje-6UJZk1jEOLV_tzNoxYX95YbABISWj1BxSpQDv3ubCo1K5eWLHLtD64HkHRlab27ZUA

### Vérifier la validité d'une agence (via Gateway)
GET http://localhost:8080/billing/AgenceBeta/valid
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc0Njc1ODQ0MCwiZXhwIjoxNzQ2NzYyMDQwfQ.UjiENMp2SAKpw2f-7_40_aSnO3IGBEHqkvvx2AM0RjE
