### Créer une souscription (via Gateway)
POST http://4.213.176.200:8080/billing
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXRzYSIsImlhdCI6MTc0ODEzNjI2NCwiZXhwIjoxNzQ4MTM5ODY0fQ.rl3eHDeka2TORFyQ35sugiJsXnp5CwIaScliOm1Cll2PhVQOjf_evPpX6cyR0Kcw-q2OZWlwjs7ndDF0FXot0uTNBkI44DMHc9o9VHHC6HH0wF5yLxXXza7sXDSnOBWRvUnC6EPTsPc2FSq7xIW3X-2SP_y7U1jR08wifYeX-IzKEhQ9ZHfmMfeZJ62_0Po1hoWEfgKx8RRa9PkzrTad1E4dQ3s1RXhHPu-as6mpuRrekizMPBIetaLGh5PNvJgsA14QNP6DdSMs2RhPWMdTBKUMe8b1In9BuSLSBsYOa6Z0d-LBkbYpa4yJ3pScFPlbg7-mJkmWyW5MkvXcwvJDHQ
Content-Type: application/json

{
  "agencyName": "AgenceBeta",
  "planType": "Standard"
}

### Lister les souscriptions (via Gateway)
GET http://192.168.122.157:8080/billing
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXRzYSIsImlhdCI6MTc0ODA0ODk0MCwiZXhwIjoxNzQ4MDUyNTQwfQ.C0JjvhkZ5dvUMpRODApIOzRaX9kdpPzraXUJx4ZuRens-ezgBymFHmShTFeaf_ScowwiPsA6hiW489zK4wBZVDC5hGPgZtvvv0wt1Cywucav0wYD2ahstyAYeAr1bJlLDsuI4GAq5DUzJIzEm0rUXq5f_EIbhdDV4CBYgI0i_X1FyIbdGlww45JGyJdG4LPlOXbpcaCqhdT4XCfHoT_f1wx-DcZCeht4FcXG8Mh5BHd1BFMbttr_tuNg0_ngZd_urcEWxdhP0WwC_3gdUWMpYrpoIZrKfeS4Z_1gVeOmHRPHC7oxLJMN6koQsDNzHUotGapS1jzias_lB4W2CJWESw

### Vérifier la validité d'une agence (via Gateway)
GET http://localhost:8080/billing/AgenceBeta/valid
Authorization: Bearer eyJraWQiOiJteS1rZXktaWQiLCJhbGciOiJSUzI1NiJ9.eyJyb2xlcyI6WyJST0xFX0FETUlOIl0sInNjb3BlcyI6WyJyZWFkIiwid3JpdGUiXSwic3ViIjoiYWRtaW4iLCJpYXQiOjE3NDg4Nzg5MzYsImV4cCI6MTc0ODg4MjUzNiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgxIn0.XluOH64mUo2yl3GQQ0Y21sReyD0Is7bfLQbdU25kefmKTv786HMlSMLWACFw6bzrfsrucbWhYHwjX3YlDrAhEb159M49W2t-1T-xK3x63b0lBH9dtvy_5XIvxanqPwqRa-VBx2n8jX6-jJT97zNI7JMn2Hj3ddA6zM-TngJLeY-aTv-31d7S_3zCfXj_r3Ilro847fsBG92k-vltaXZ-3II-OnaZbuyYCBFst16Th_s-CJ6RJ3vTKh0k77NIVAP6zGykWNFdSNVBiPAgA81hOtjyObbfDnhFxIc8CWyCdRGLJcxr_kEV75TGKEivgyNi0QWk4_xEXh2WBJptl3xcQg 

### Appeler Billing sécurisé (via Gateway)
POST http://localhost:8080/billing/create
Authorization: Bearer eyJraWQiOiJteS1rZXktaWQiLCJhbGciOiJSUzI1NiJ9.eyJyb2xlcyI6WyJST0xFX0FETUlOIl0sInNjb3BlcyI6WyJyZWFkIiwid3JpdGUiXSwic3ViIjoiYWRtaW4iLCJpYXQiOjE3NDg5MDAyNzEsImV4cCI6MTc0ODkwMzg3MSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgxIn0.E6mDtlPAbBqwYj5bZCYAUTKX2KvQh_Kupl5z00auY-rQa3-dq6msletVOIMSTY4UzI-YAiSJbhOEbN-tqdLXMHFQHTc3cNrx-xuUQKmCj27MRTmqp36WRWyhD6PS2kLvzsVp_yKhv6JcDYkAj020djutDCl_eJQeXcs161uvFPr_VbRQz963KhWNeNDuxAF4wPVTn9WAOCd5tmZJK2MoPUzAIVMRHDOAJ8_aOIrjdHwVC_EHzwIsxGBXQ8MT_nO91vZ7JOBPxn4qvekAR_F98KFXgz6QhuV_TpiQYCx_PWOYs2dlfNbhD_8SSiq3nv2tHecSFNV776REq_20DlOv4Q  
Content-Type: application/json

{
  "agencyName": "AgenceBeta",
  "planType": "Standard"
}