### Créer une réservation via Gateway
POST http://192.168.122.157:8080/reservations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXRzYSIsImlhdCI6MTc0ODA0ODk0MCwiZXhwIjoxNzQ4MDUyNTQwfQ.C0JjvhkZ5dvUMpRODApIOzRaX9kdpPzraXUJx4ZuRens-ezgBymFHmShTFeaf_ScowwiPsA6hiW489zK4wBZVDC5hGPgZtvvv0wt1Cywucav0wYD2ahstyAYeAr1bJlLDsuI4GAq5DUzJIzEm0rUXq5f_EIbhdDV4CBYgI0i_X1FyIbdGlww45JGyJdG4LPlOXbpcaCqhdT4XCfHoT_f1wx-DcZCeht4FcXG8Mh5BHd1BFMbttr_tuNg0_ngZd_urcEWxdhP0WwC_3gdUWMpYrpoIZrKfeS4Z_1gVeOmHRPHC7oxLJMN6koQsDNzHUotGapS1jzias_lB4W2CJWESw

{
  "travelerName": "David",
  "destination": "Berlin",
  "agencyName": "AgenceDelta"
}

### Lister les réservations via Gateway
GET http://192.168.122.157:8080/reservations
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXRzYSIsImlhdCI6MTc0NzgzNDExNiwiZXhwIjoxNzQ3ODM3NzE2fQ.SoPdl3qp3WoeTrs55Av5Nxxc6N7XeOe9P1raVP5RiPbg9m0GLlntl-VcdZgAnESZmRrnzEeOBb3xiuM--eK9fIHDFOH6MYOy-00ayI0QnJG2zuciNS-vpGXKzqUYnyT8FnUudkfv-J1QsX9nJcSQSowevce4bQGBAk4KbJlqc5-B57dj7aCfxd47fLiyde_CbV7rD9m-ShhJUSouTTE11mtEFfZUHkBJsWlX_Kq-CfwWchNq0paF0yoFz17nbHfW4a9yq5VbTSJQl00TcmwTFaKvQKHlS9D7-LSLfM_-f1UBNqDr8ufs5defYwOj0BlbUASg6CS_jDdke0erDIUF8g
