### Créer une réservation via Gateway
POST http://localhost:8080/reservations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXRzYSIsImlhdCI6MTc0NzY5OTI2OCwiZXhwIjoxNzQ3NzAyODY4fQ.ItVcAg62LHJygGOz04SP1UQyyQO64URg38Iub9FAcYwyT9NcQOBqMtQ6ZrCZV8a3RdXkgkTVygDQctTrjqpmBPFB_vd-0W0p-qFjqToT_-hYS6LQiLOQX_mIk7I1k4MIz2QJQcUGcY6015zCn015Ep4iD-gLQkeRq3qG26q8FNESTR1mLQv88XtItEIkRaIfwduxnayJCMm2pBAExitzQ1uZXT_5J_V1EloEP0x4z3KzUwvdBihy-fppHwdfidu51FCgEj8fB_XFbUKfZEo5ipGznmMywx--pu_qOXqQC8VPkGKXbu9VPPQMIIR8x-9eyqxyPV-MH3fNaVGFTdATwA

{
  "travelerName": "David",
  "destination": "Berlin",
  "agencyName": "AgenceDelta"
}

### Lister les réservations via Gateway
GET http://localhost:8080/reservations
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXRzYSIsImlhdCI6MTc0NzY5NTU2MywiZXhwIjoxNzQ3Njk5MTYzfQ.Vd5iARqv_Ktln7DXFJDKPQgZQn3G-TpBDwDcqrdPAmjQ6NrztkYM0Hr3i9afVkF8XQ3NpzYcAJvhgz8DlSePwLFMk8VZg9wbSQ3cCBDjvVv4zXK-i7yobStbjKiZiwjSxYxOOKLngnWdt4LGPJK9yU7mHm3yjJYSk_LLmNC9Z-J8Yca-vUrY0906W74azaMAgOZdzbxmO3NUmkdEaXyEuv8-lWalM5KklGTUIN0vnn_0501rwNefGv1375YLsZDU-4ZcdMnKbHWdFKKbx2SleZ9B7TpprVxTZkzw61KQ01Inbdh-mCNBEjuBpelc1iRhe8gYFz2rhgHKbGHMx_0ByA
